version: '3.9'

services:
    vote_backend:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8010
        volumes:
            - ../:/usr/src/app/
        ports:
            - "8002:8010"
        env_file:
            - ../.env
        networks:
            - vote
        depends_on:
            - vote_postgres_db
            
    vote_postgres_db:
        build:
            context: ../config_db
            dockerfile: Dockerfile
        volumes:
            - ../db/postgres-data-vote:/var/lib/postgresql/data-vote
        ports:
            - "5433:5432"
        env_file:
            - ../.env
        networks:
            - vote

networks:
    vote:
        external: True