version: '3.9'

services:
    vote_backend:
        build:
            context: ..
            dockerfile: docker/Dockerfile.dev
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8010
        volumes:
            - ../:/usr/src/app/
        ports:
            - "8002:8010"
        env_file:
            - ../.env
        networks:
            - vote_red
        depends_on:
            - vote_db
            
    vote_db: 
        container_name: 'db-votaciones'
        image: postgres:15.0
        ports:
            - '5433:5433'
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        networks:
            - vote_red
        volumes:
            - ./db/postgres-data:/var/lib/postgresql/data

networks:
    vote_red:
        external: True